package org.iproduct.eshop.jpa.entity;

//
// This file was generated by the JPA Modeler
//
import java.io.Serializable;
import java.lang.String;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.TableGenerator;
import javax.validation.constraints.NotNull;

@Entity
public class Book implements Serializable {

    @TableGenerator(name = "book_gen",
            table = "id_gen",
            pkColumnName = "GEN_KEY",
            valueColumnName = "GEN_VALUE",
            pkColumnValue = "book_id",
            allocationSize = 1
    )
    @Id
    @NotNull
    @GeneratedValue(strategy = GenerationType.TABLE, generator = "book_gen")
    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    private Long id;
    
    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private String title;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private double percentage_off = 0;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private double price;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @ElementCollection
    private List<String> author;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private String isbn;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private String book_url;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 1024, scale = 0, precision = 0)
    @Basic
    private String description;

    @ManyToOne(cascade = CascadeType.PERSIST, targetEntity = Publisher.class)
    private Publisher publisher;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private boolean onsale = false;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private String photo_url;

    public Book() {
    }

    public Book(String title, String author, Publisher publisher, double price) {
        this.price = price;
        this.author = new ArrayList<>();
        this.author.add(author);
        this.title = title;
        this.publisher = publisher;
    }

    public Book( String title, String[] authors, Publisher publisher, double price) {
        this.price = price;
        this.author = Arrays.asList(authors);
        this.title = title;
        this.publisher = publisher;
    }

    public Book(String title, String isbn, String[] authors, String description, 
            Publisher publisher, String photoUrl, String bookUrl, double price, double percentage_off) {
        this.percentage_off = percentage_off;
        this.price = price;
        this.author = Arrays.asList(authors);
        this.isbn = isbn;
        this.title = title;
        this.book_url = bookUrl;
        this.description = description;
        this.publisher = publisher;
        this.photo_url = photoUrl;
        this.book_url = bookUrl;
    }

    
    public double getPercentage_off() {
        return this.percentage_off;
    }

    public void setPercentage_off(double percentage_off) {
        this.percentage_off = percentage_off;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public List<String> getAuthor() {
        return this.author;
    }

    public void setAuthor(List<String> author) {
        this.author = author;
    }

    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBookUrl() {
        return this.book_url;
    }

    public void setBookUrl(String book_url) {
        this.book_url = book_url;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Publisher getPublishers() {
        return this.publisher;
    }

    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean isOnsale() {
        return this.onsale;
    }

    public void setOnsale(boolean onsale) {
        this.onsale = onsale;
    }

    public String getPhotoUrl() {
        return this.photo_url;
    }

    public void setPhotoUrl(String photo_url) {
        this.photo_url = photo_url;
    }

    @Override
    public String toString() {
        return "Book{" + "percentage_off=" + percentage_off + ", price=" + price + ", author=" + author + ", isbn=" + isbn + ", title=" + title + ", book_url=" + book_url + ", description=" + description + ", publisher=" + publisher + ", id=" + id + ", onsale=" + onsale + ", photo_url=" + photo_url + '}';
    }
}
